# Understanding numpy arrays

Numpy arrays are stored in contiguous memory as opposed to Python lists. The numpy library has a C-backend making it much faster.

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])

print(a)
print("shape:", a.shape)
print("dtype:", a.dtype)

### Shape

Numpy arrays can be have as many dimensions as you want.

In [ ]:
a = np.ones((5,5), "int64")

print(a)
print(a.shape)

Numpy arrays can be reshaped.

In [ ]:
a = np.arange(12).reshape((4, 3))

print(a)

### Indexing

You can access indices of a numpy array in many ways.

In [23]:
a = np.arange(9).reshape((3,3))

print("a:")
print(a)

print("Print all of a:")
print(a[:])

print("Print first row:")
print(a[0])

print("Print first element:")
print(a[0][0])

print("Cut out:")
print(a[1:])

print("Up to:")
print(a[:1])

print("Nested cut out:")
print(a[1:,1:])

print("Nested cut out 2:")
print(a[:,1:])

print("Negative up to:")
print(a[:,:-1])


a:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Print all of a:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Print first row:
[0 1 2]
Print first element:
0
Cut out:
[[3 4 5]
 [6 7 8]]
Up to:
[[0 1 2]]
Nested cut out:
[[4 5]
 [7 8]]
Nested cut out 2:
[[1 2]
 [4 5]
 [7 8]]
Negative up to:
[[0 1]
 [3 4]
 [6 7]]
